version: '3.9'

networks:
  clientesNetwork:
    driver: bridge

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./BDD:/docker-entrypoint-initdb.d
      - ./database_check.sh:/database_check.sh
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "/database_check.sh" ]
      interval: 20s
      timeout: 10s
      retries: 50
    networks:
      - clientesNetwork

  web:
    build: .
    ports:
      - "8080:8080"

    links:
      - db
    depends_on:
      db:
        condition: service_healthy

    entrypoint: sh -c "/code/init.sh"

    networks:
      - clientesNetwork

